---
# Apply to all hosts
- hosts: all
# Become superuser with sudo
  become: yes

  tasks:
  - name: Ensure chrony (for time syncronization) is installed.
    dnf:
      name: chrony
      state: present
  - name: Ensure chrony is running
    service:
      name: chronyd
      state: started
      enabled: yes

